#!/bin/bash

language=$1
year=$2
day=$3
part=$4

# Check the length of the day input
# Prepend a 0 if it's less than 10 i.e 4 -> 04, 11 -> 11
if [ ${#day} -le 1 ]; then
    day=0$day
fi

script_dir=$year/day_$day/$language
cd $script_dir

run_python () {
    source_file=p$part.py
    printf "Running $script_dir/$source_file\n-----\n"
    python $source_file
}

run_haskell () {
    source_file=p$part.hs
    output_file=p$part.hsx
    printf "Attempting to build $source_file"
    stack ghc -- $source_file -o $output_file
    if [ $? -eq 0 ]; then
        printf "Running $script_dir/$output_file\n-----\n"
        ./$output_file
    else
        printf "Failed to build $source_file, not running"
        exit 1
    fi
}

run_ruby () {
    source_file=p$part.rb
    printf "Running $script_dir/$source_file\n-----\n"
    ruby $source_file
}

case $language in
    "python") run_python;;
    "haskell") run_haskell;;
    "ruby") run_ruby;;
    *) echo "No problems have been solved in the language $language"; exit 1;;
esac
