#!/bin/sh

# Check the length of the day input
# Prepend a 0 if it's less than 10 i.e 4 -> 04, 11 -> 11
day=$3
if [ ${#3} -le 1 ]; then
    day=0$3
fi

cd $2/day_$day/

if [ $1 = "haskell" ]; then
    source_file=p$4.hs
    output_file=p$4.hsx
    stack ghc -- $source_file -o $output_file
    if [ $? -eq 0 ]; then
        echo "Running $2/day_$day/$output_file\n-----\n"
        ./$output_file
    else
        echo "Failed to build $source_file, not running."
    fi
elif [ $1 = "python" ]; then
    source_file=p$4.py
    echo "Running $2/day_$day/$output_file\n-----\n"
    python3 p$4.py
elif [ $1 = "ruby" ]; then
    source_file=p$4.rb
    echo "Running $2/day_$day/$output_file\n-----\n"
    ruby p$4.rb
fi
